version: '3'
services:
  top.api:
    image: ghcr.io/settimov7/nestjs-top-app/nestjs-top-app:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
