version: '3'
services:
  top.api:
    image:
    container_name: ghcr.io/settimov7/nestjs-top-app/nestjs-top-app:develop
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
