name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          name: Settimov7/nestjs-top-app/nestjs-top-app
          tags: "develop"
